# Generated by Django 5.0.1 on 2024-01-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bannier_sous_titre_bannier_bannier_texte_bannier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
