# Generated by Django 5.0.1 on 2024-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_reservation_r_provenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='r_adresse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='r_piece_nationale',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
