# Generated by Django 5.0.1 on 2024-08-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_reservation_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payement',
            field=models.BooleanField(default=False),
        ),
    ]
