# Generated by Django 5.0.1 on 2024-08-04 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_reservation_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user_id',
        ),
    ]
