# Generated by Django 5.0.1 on 2024-08-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_reservation_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user_id',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
